export const LOAD_ITEMS_SUCCESS = 'LOAD_ITEMS_SUCCESS'
export const DELETE_ITEM_SUCCESS = 'DELETE_ITEM_SUCCESS'
export const ADD_ITEM_SUCCESS = 'ADD_ITEM_SUCCESS'
export const EDIT_ITEM_SUCCESS = 'EDIT_ITEM_SUCCESS'
